/*
 *   Copyright (c) 2006-2010 Marvisan Pty. Ltd. All rights reserved.
 *               Use is subject to license terms.
 */

/*
 * Country.java
 *
 * $Id: Country.java,v 1.5 2011-10-29 09:42:33 vrotaru Exp $
 */
package net.hades.fix.message.type;

import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * ISO country code.
 *
 * @author <a href="mailto:support@marvisan.com">Support Team</a>
 * @version $Revision: 1.5 $
 * @created 05/09/2009, 4:49:20 PM
 */
@XmlType
@XmlEnum(String.class)
public enum Country {

    @XmlEnumValue("AX") AalandIslands               ("AX"),
    @XmlEnumValue("AF") Afghanistan                 ("AF"),
    @XmlEnumValue("AL") Albania                     ("AL"),
    @XmlEnumValue("DZ") Algeria                     ("DZ"),
    @XmlEnumValue("AS") AmericanSamoa               ("AS"),
    @XmlEnumValue("AD") Andorra                     ("AD"),
    @XmlEnumValue("AO") Angola                      ("AO"),
    @XmlEnumValue("AI") Anguilla                    ("AI"),
    @XmlEnumValue("AQ") Antarctica                  ("AQ"),
    @XmlEnumValue("AG") AntiguaAndBarbuda           ("AG"),
    @XmlEnumValue("AR") Argentina                   ("AR"),
    @XmlEnumValue("AM") Armenia                     ("AM"),
    @XmlEnumValue("AW") Aruba                       ("AW"),
    @XmlEnumValue("AU") Australia                   ("AU"),
    @XmlEnumValue("AT") Austria                     ("AT"),
    @XmlEnumValue("AZ") Azerbaijan                  ("AZ"),
    @XmlEnumValue("BS") Bahamas                     ("BS"),
    @XmlEnumValue("BH") Bahrain                     ("BH"),
    @XmlEnumValue("BD") Bangladesh                  ("BD"),
    @XmlEnumValue("BB") Barbados                    ("BB"),
    @XmlEnumValue("BY") Belarus                     ("BY"),
    @XmlEnumValue("BE") Belgium                     ("BE"),
    @XmlEnumValue("BZ") Belize                      ("BZ"),
    @XmlEnumValue("BJ") Benin                       ("BJ"),
    @XmlEnumValue("BM") Bermuda                     ("BM"),
    @XmlEnumValue("BT") Bhutan                      ("BT"),
    @XmlEnumValue("BO") Bolivia                     ("BO"),
    @XmlEnumValue("BA") BosniaAndHerzegovina        ("BA"),
    @XmlEnumValue("BW") Botswana                    ("BW"),
    @XmlEnumValue("BV") BouvetIsland                ("BV"),
    @XmlEnumValue("BR") Brazil                      ("BR"),
    @XmlEnumValue("IO") BritishIndianOceanTerritory ("IO"),
    @XmlEnumValue("VG") BritishVirginIslands        ("VG"),
    @XmlEnumValue("BN") Brunei                      ("BN"),
    @XmlEnumValue("BG") Bulgaria                    ("BG"),
    @XmlEnumValue("BF") BurkinaFaso                 ("BF"),
    @XmlEnumValue("BI") Burundi                     ("BI"),
    @XmlEnumValue("KH") Cambodia                    ("KH"),
    @XmlEnumValue("CM") Cameroon                    ("CM"),
    @XmlEnumValue("CA") Canada                      ("CA"),
    @XmlEnumValue("CV") CapeVerde                   ("CV"),
    @XmlEnumValue("KY") CaymanIslands               ("KY"),
    @XmlEnumValue("CF") CentralAfricanRepublic      ("CF"),
    @XmlEnumValue("TD") Chad                        ("TD"),
    @XmlEnumValue("CL") Chile                       ("CL"),
    @XmlEnumValue("CN") China                       ("CN"),
    @XmlEnumValue("CX") ChristmasIsland             ("CX"),
    @XmlEnumValue("CC") CocosIslands                ("CC"),
    @XmlEnumValue("CO") Colombia                    ("CO"),
    @XmlEnumValue("KM") Comoros                     ("KM"),
    @XmlEnumValue("CG") Congo                       ("CG"),
    @XmlEnumValue("CK") CookIslands                 ("CK"),
    @XmlEnumValue("CR") CostaRica                   ("CR"),
    @XmlEnumValue("CI") IvoryCoast                  ("CI"),
    @XmlEnumValue("CU") Cuba                        ("CU"),
    @XmlEnumValue("CY") Cyprus                      ("CY"),
    @XmlEnumValue("CZ") CzechRepublic               ("CZ"),
    @XmlEnumValue("DK") Denmark                     ("DK"),
    @XmlEnumValue("DJ") Djibouti                    ("DJ"),
    @XmlEnumValue("DM") Dominica                    ("DM"),
    @XmlEnumValue("DO") DominicanRepublic           ("DO"),
    @XmlEnumValue("EC") Ecuador                     ("EC"),
    @XmlEnumValue("EG") Egypt                       ("EG"),
    @XmlEnumValue("SV") ElSalvador                  ("SV"),
    @XmlEnumValue("GQ") EquatorialGuinea            ("GQ"),
    @XmlEnumValue("ER") Eritrea                     ("ER"),
    @XmlEnumValue("EE") Estonia                     ("EE"),
    @XmlEnumValue("ET") Ethiopia                    ("ET"),
    @XmlEnumValue("FO") FaeroeIslands               ("FO"),
    @XmlEnumValue("FK") FalklandIslands             ("FK"),
    @XmlEnumValue("FJ") Fiji                        ("FJ"),
    @XmlEnumValue("FI") Finland                     ("FI"),
    @XmlEnumValue("FR") France                      ("FR"),
    @XmlEnumValue("GF") FrenchGuiana                ("GF"),
    @XmlEnumValue("PF") FrenchPolynesia             ("PF"),
    @XmlEnumValue("TF") FrenchSouthernTerritories   ("TF"),
    @XmlEnumValue("GA") Gabon                       ("GA"),
    @XmlEnumValue("GM") Gambia                      ("GM"),
    @XmlEnumValue("GE") Georgia                     ("GE"),
    @XmlEnumValue("DE") Germany                     ("DE"),
    @XmlEnumValue("GH") Ghana                       ("GH"),
    @XmlEnumValue("GI") Gibraltar                   ("GI"),
    @XmlEnumValue("GR") Greece                      ("GR"),
    @XmlEnumValue("GL") Greenland                   ("GL"),
    @XmlEnumValue("GD") Grenada                     ("GD"),
    @XmlEnumValue("GP") Guadaloupe                  ("GP"),
    @XmlEnumValue("GU") Guam                        ("GU"),
    @XmlEnumValue("GT") Guatemala                   ("GT"),
    @XmlEnumValue("GN") Guinea                      ("GN"),
    @XmlEnumValue("GW") GuineaBissau                ("GW"),
    @XmlEnumValue("GY") Guyana                      ("GY"),
    @XmlEnumValue("HT") Haiti                       ("HT"),
    @XmlEnumValue("HM") HeardAndMcDonaldIslands     ("HM"),
    @XmlEnumValue("VA") HolySee                     ("VA"),
    @XmlEnumValue("HN") Honduras                    ("HN"),
    @XmlEnumValue("HK") HongKong                    ("HK"),
    @XmlEnumValue("HR") Croatia                     ("HR"),
    @XmlEnumValue("HU") Hungary                     ("HU"),
    @XmlEnumValue("IS") Iceland                     ("IS"),
    @XmlEnumValue("IN") India                       ("IN"),
    @XmlEnumValue("ID") Indonesia                   ("ID"),
    @XmlEnumValue("IR") Iran                        ("IR"),
    @XmlEnumValue("IQ") Iraq                        ("IQ"),
    @XmlEnumValue("IE") Ireland                     ("IE"),
    @XmlEnumValue("IL") Israel                      ("IL"),
    @XmlEnumValue("IT") Italy                       ("IT"),
    @XmlEnumValue("JM") Jamaica                     ("JM"),
    @XmlEnumValue("JP") Japan                       ("JP"),
    @XmlEnumValue("JO") Jordan                      ("JO"),
    @XmlEnumValue("KZ") Kazakhstan                  ("KZ"),
    @XmlEnumValue("KE") Kenya                       ("KE"),
    @XmlEnumValue("KI") Kiribati                    ("KI"),
    @XmlEnumValue("KP") NorthKorea                  ("KP"),
    @XmlEnumValue("KR") SouthKorea                  ("KR"),
    @XmlEnumValue("KW") Kuwait                      ("KW"),
    @XmlEnumValue("KG") KyrgyzRepublic              ("KG"),
    @XmlEnumValue("LA") Lao                         ("LA"),
    @XmlEnumValue("LV") Latvia                      ("LV"),
    @XmlEnumValue("LB") Lebanon                     ("LB"),
    @XmlEnumValue("LS") Lesotho                     ("LS"),
    @XmlEnumValue("LR") Liberia                     ("LR"),
    @XmlEnumValue("LY") Libya                       ("LY"),
    @XmlEnumValue("LI") Liechtenstein               ("LI"),
    @XmlEnumValue("LT") Lithuania                   ("LT"),
    @XmlEnumValue("LU") Luxembourg                  ("LU"),
    @XmlEnumValue("MO") Macao                       ("MO"),
    @XmlEnumValue("MK") Macedonia                   ("MK"),
    @XmlEnumValue("MG") Madagascar                  ("MG"),
    @XmlEnumValue("MW") Malawi                      ("MW"),
    @XmlEnumValue("MY") Malaysia                    ("MY"),
    @XmlEnumValue("MV") Maldives                    ("MV"),
    @XmlEnumValue("ML") Mali                        ("ML"),
    @XmlEnumValue("MT") Malta                       ("MT"),
    @XmlEnumValue("MH") MarshallIslands             ("MH"),
    @XmlEnumValue("MQ") Martinique                  ("MQ"),
    @XmlEnumValue("MR") Mauritania                  ("MR"),
    @XmlEnumValue("MU") Mauritius                   ("MU"),
    @XmlEnumValue("YT") Mayotte                     ("YT"),
    @XmlEnumValue("MX") Mexico                      ("MX"),
    @XmlEnumValue("FM") Micronesia                  ("FM"),
    @XmlEnumValue("MD") Moldova                     ("MD"),
    @XmlEnumValue("MC") Monaco                      ("MC"),
    @XmlEnumValue("MN") Mongolia                    ("MN"),
    @XmlEnumValue("MS") Montserrat                  ("MS"),
    @XmlEnumValue("MA") Morocco                     ("MA"),
    @XmlEnumValue("MZ") Mozambique                  ("MZ"),
    @XmlEnumValue("MM") Myanmar                     ("MM"),
    @XmlEnumValue("NA") Namibia                     ("NA"),
    @XmlEnumValue("NR") Nauru                       ("NR"),
    @XmlEnumValue("NP") Nepal                       ("NP"),
    @XmlEnumValue("AN") NetherlandsAntilles         ("AN"),
    @XmlEnumValue("NL") Netherlands                 ("NL"),
    @XmlEnumValue("NC") NewCaledonia                ("NC"),
    @XmlEnumValue("NZ") NewZealand                  ("NZ"),
    @XmlEnumValue("NI") Nicaragua                   ("NI"),
    @XmlEnumValue("NE") Niger                       ("NE"),
    @XmlEnumValue("NG") Nigeria                     ("NG"),
    @XmlEnumValue("NU") Niue                        ("NU"),
    @XmlEnumValue("NF") NorfolkIsland               ("NF"),
    @XmlEnumValue("MP") NorthernMarianaIslands      ("MP"),
    @XmlEnumValue("NO") Norway                      ("NO"),
    @XmlEnumValue("OM") Oman                        ("OM"),
    @XmlEnumValue("PK") Pakistan                    ("PK"),
    @XmlEnumValue("PW") Palau                       ("PW"),
    @XmlEnumValue("PS") PalestinianTerritory        ("PS"),
    @XmlEnumValue("PA") Panama                      ("PA"),
    @XmlEnumValue("PG") PapuaNewGuinea              ("PG"),
    @XmlEnumValue("PY") Paraguay                    ("PY"),
    @XmlEnumValue("PE") Peru                        ("PE"),
    @XmlEnumValue("PH") Philippines                 ("PH"),
    @XmlEnumValue("PN") PitcairnIsland              ("PN"),
    @XmlEnumValue("PL") Poland                      ("PL"),
    @XmlEnumValue("PT") Portugal                    ("PT"),
    @XmlEnumValue("PR") PuertoRico                  ("PR"),
    @XmlEnumValue("QA") Qatar                       ("QA"),
    @XmlEnumValue("RE") Reunion                     ("RE"),
    @XmlEnumValue("RO") Romania                     ("RO"),
    @XmlEnumValue("RU") RussianFederation           ("RU"),
    @XmlEnumValue("RW") Rwanda                      ("RW"),
    @XmlEnumValue("SH") StHelena                    ("SH"),
    @XmlEnumValue("KN") StKittsAndNevis             ("KN"),
    @XmlEnumValue("LC") StLucia                     ("LC"),
    @XmlEnumValue("PM") StPierreAndMiquelon         ("PM"),
    @XmlEnumValue("VC") StVincentAndGrenadines      ("VC"),
    @XmlEnumValue("WS") Samoa                       ("WS"),
    @XmlEnumValue("SM") SanMarino                   ("SM"),
    @XmlEnumValue("ST") SaoTomeAndPrincipe          ("ST"),
    @XmlEnumValue("SA") SaudiArabia                 ("SA"),
    @XmlEnumValue("SN") Senegal                     ("SN"),
    @XmlEnumValue("CS") SerbiaAndMontenegro         ("CS"),
    @XmlEnumValue("SC") Seychelles                  ("SC"),
    @XmlEnumValue("SL") SierraLeone                 ("SL"),
    @XmlEnumValue("SG") Singapore                   ("SG"),
    @XmlEnumValue("SK") Slovakia                    ("SK"),
    @XmlEnumValue("SI") Slovenia                    ("SI"),
    @XmlEnumValue("SB") SolomonIslands              ("SB"),
    @XmlEnumValue("SO") Somalia                     ("SO"),
    @XmlEnumValue("ZA") SouthAfrica                 ("ZA"),
    @XmlEnumValue("GS") SouthGeorgia                ("GS"),
    @XmlEnumValue("ES") Spain                       ("ES"),
    @XmlEnumValue("LK") SriLanka                    ("LK"),
    @XmlEnumValue("SD") Sudan                       ("SD"),
    @XmlEnumValue("SR") Suriname                    ("SR"),
    @XmlEnumValue("SJ") SvalbardAndJanMayen         ("SJ"),
    @XmlEnumValue("SZ") Swaziland                   ("SZ"),
    @XmlEnumValue("SE") Sweden                      ("SE"),
    @XmlEnumValue("CH") Switzerland                 ("CH"),
    @XmlEnumValue("SY") SyrianArabRepublic          ("SY"),
    @XmlEnumValue("TW") Taiwan                      ("TW"),
    @XmlEnumValue("TJ") Tajikistan                  ("TJ"),
    @XmlEnumValue("TZ") Tanzania                    ("TZ"),
    @XmlEnumValue("TH") Thailand                    ("TH"),
    @XmlEnumValue("TL") Timor                       ("TL"),
    @XmlEnumValue("TG") Togo                        ("TG"),
    @XmlEnumValue("TK") Tokelau                     ("TK"),
    @XmlEnumValue("TO") Tonga                       ("TO"),
    @XmlEnumValue("TT") TrinidadAndTobago           ("TT"),
    @XmlEnumValue("TN") Tunisia                     ("TN"),
    @XmlEnumValue("TR") Turkey                      ("TR"),
    @XmlEnumValue("TM") Turkmenistan                ("TM"),
    @XmlEnumValue("TC") TurksAndCaicosIslands       ("TC"),
    @XmlEnumValue("TV") Tuvalu                      ("TV"),
    @XmlEnumValue("VI") USVirginIslands             ("VI"),
    @XmlEnumValue("UG") Uganda                      ("UG"),
    @XmlEnumValue("UA") Ukraine                     ("UA"),
    @XmlEnumValue("AE") UnitedArabEmirates          ("AE"),
    @XmlEnumValue("GB") UnitedKingdom               ("GB"),
    @XmlEnumValue("UM") UnitedStatesMinor           ("UM"),
    @XmlEnumValue("US") USA                         ("US"),
    @XmlEnumValue("UY") Uruguay                     ("UY"),
    @XmlEnumValue("UZ") Uzbekistan                  ("UZ"),
    @XmlEnumValue("VU") Vanuatu                     ("VU"),
    @XmlEnumValue("VE") Venezuela                   ("VE"),
    @XmlEnumValue("VN") VietNam                     ("VN"),
    @XmlEnumValue("WF") WallisAndFutunaIslands      ("WF"),
    @XmlEnumValue("EH") WesternSahara               ("EH"),
    @XmlEnumValue("YE") Yemen                       ("YE"),
    @XmlEnumValue("ZM") Zambia                      ("ZM"),
    @XmlEnumValue("ZW") Zimbabwe                    ("ZW");

    private static final long serialVersionUID = 1L;

    private String value;

    private static final Map<String, Country> stringToEnum = new HashMap<String, Country>();

    static {
        for (Country tag : values()) {
            stringToEnum.put(tag.getValue(), tag);
        }
    }

    /** Creates a new instance of Country */
    Country(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static Country valueFor(String value) {
        return stringToEnum.get(value);
    }
}
