/*
 *   Copyright (c) 2006-2012 Marvisan Pty. Ltd. All rights reserved.
 *               Use is subject to license terms.
 */

/*
 * ErrorDetailsView.java
 *
 * Created on 19/02/2012, 12:06:09 PM
 */
package net.hades.fix.admin.gui.view;

import javax.swing.UIManager;

/**
 * Error details view.
 *
 * @author <a href="mailto:support@marvisan.com">Support Team</a>
 * @version $Revision: 1.1 $
 */
public class ErrorDetailsView extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    
    private String id;
    private String error;
    private String stack;
    private boolean onlyError;

    public ErrorDetailsView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ErrorDetailsView(java.awt.Frame parent, String id, String error, String stack) {
        super(parent, true);
        this.id = id;
        this.error = error;
        this.stack = stack;
        initComponents();
    }
    
    public ErrorDetailsView(java.awt.Frame parent, String id, String error) {
        super(parent, true);
        this.id = id;
        this.stack = error;
        onlyError = true;
        initComponents();
    }

    public String getError() {
        return error;
    }

    public String getStack() {
        return stack;
    }

    public boolean isOnlyError() {
        return onlyError;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane3 = new javax.swing.JScrollPane();
        errorMessageLabel = new javax.swing.JLabel();
        errorMessageScrollPane = new javax.swing.JScrollPane();
        errorMessageTextPane = new javax.swing.JTextPane();
        errorStackLabel = new javax.swing.JLabel();
        errorStackScrollPane = new javax.swing.JScrollPane();
        errorStackTextPane = new javax.swing.JTextPane();
        exitlButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("net/hades/fix/admin/gui/resources/HadesAdminConsole"); // NOI18N
        setTitle(bundle.getString("ErrorDetailsView.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        errorMessageLabel.setText(bundle.getString("ErrorDetailsView.errorMessageLabel.text")); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        getContentPane().add(errorMessageLabel, gridBagConstraints);

        errorMessageScrollPane.setMinimumSize(new java.awt.Dimension(400, 50));
        errorMessageScrollPane.setPreferredSize(new java.awt.Dimension(400, 50));

        errorMessageTextPane.setEditable(false);
        errorMessageTextPane.setText(getError());
        errorMessageTextPane.setMinimumSize(new java.awt.Dimension(400, 50));
        errorMessageTextPane.setName("");
        errorMessageTextPane.setPreferredSize(new java.awt.Dimension(400, 50));
        errorMessageScrollPane.setViewportView(errorMessageTextPane);
        errorMessageTextPane.setVisible(!onlyError);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(errorMessageScrollPane, gridBagConstraints);
        errorMessageScrollPane.setVisible(!onlyError);

        errorStackLabel.setText(bundle.getString("ErrorDetailsView.errorStackLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        getContentPane().add(errorStackLabel, gridBagConstraints);
        errorStackLabel.setVisible(!onlyError);

        errorStackScrollPane.setMinimumSize(new java.awt.Dimension(400, 500));
        errorStackScrollPane.setPreferredSize(new java.awt.Dimension(400, 500));

        errorStackTextPane.setEditable(false);
        errorStackTextPane.setText(getStack());
        errorStackTextPane.setMinimumSize(new java.awt.Dimension(400, 500));
        errorStackTextPane.setName("");
        errorStackTextPane.setPreferredSize(new java.awt.Dimension(400, 500));
        errorStackScrollPane.setViewportView(errorStackTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        getContentPane().add(errorStackScrollPane, gridBagConstraints);

        exitlButton.setText(bundle.getString("ErrorDetailsView.exitButton.text")); // NOI18N
        exitlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitlButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(exitlButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitlButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_exitlButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ErrorDetailsView dialog = new ErrorDetailsView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JScrollPane errorMessageScrollPane;
    private javax.swing.JTextPane errorMessageTextPane;
    private javax.swing.JLabel errorStackLabel;
    private javax.swing.JScrollPane errorStackScrollPane;
    private javax.swing.JTextPane errorStackTextPane;
    private javax.swing.JButton exitlButton;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
